### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2670]
It seems facebook login doesnt work for new facebook apps. It works fine for yclas.com and websites created before the latest Facebook security issues, so it can't be related to the libraries we use.

**Comment by neo22s** [comment]
We have a big issue with this.

We need to explain to customers that it's not our issue.

Please let's check for solutions but in the meantime let's put a note in the docs.

"Due to last security events on Facebook, they are not allowing new applications to use the login system, we are working to restore this functionality but it does not depend on us."

**Comment by neo22s** [comment]
A "hack" would be that all the webs hosted on yclas if they do not setup facebook to use our own app? or it's a really bad idea?

**Comment by kotsios5** [comment]
> A "hack" would be that all the webs hosted on yclas if they do not setup facebook to use our own app? or it's a really bad idea?

Seems not possible.. Each Facebook app requires to specify only one Website -> Site URL and in the Facebook login Settings just one "Deauthorize Callback URL".

**Comment by neo22s** [comment]
Well we could redirect them to our site, and then send the details to the site back....only thing I can think off.

**Comment by kotsios5** [comment]
It sounds possible. I can't think of any reason that it wouldn't work.
