### ISSUE TITLE
Kohana Error: Not an image or invalid image

### ISSUE THREAD

**Issue by DonPramis** [yclas/yclas#2754]
Im having this error on my code, can anyone advise what is the cause of the error

```ERROR: Kohana_Exception [ 0 ]: Not an image or invalid image: ~ APPPATH/kohana/modules/image/classes/Kohana/Image.php [ 112 ] in /home/linkin12/public_html/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110```

According to Errotan(author) of Kohana this is his answer.
This is that line:

```throw new Kohana_Exception('Not an image or invalid image: :file', [':file' => Debug::path($file)]);```

```In your error line there is nothing after "image:" so your $file variable is empty at that point.```

**Screenshot of the error:**  https://i.imgsafe.org/59/59844b319f.png

Thanks

**Comment by DonPramis** [comment]
Errotan also added:

When you create the Image object, the constructor arg is the file name. Eg.:

```$a = new Image_GD($file_path);```

```Your $file_path variable is empty.```

I show him the php file and he confirm to me the issue.

I hope this will help.

Thanks

**Comment by neo22s** [comment]
As indicated in the message the Image it's not valid. Someone is trying to upload not valid images, due to size or corrupted or any other reason.

I am the one who forked koseven.... Errotan it's a collaborator oof kpseven like I am.

If you want support please buy support. This is for developers. Not for support. For that we have other ways.

Next time I will just block you if you do not follow the rules.

thanks.
