### ISSUE TITLE
Responsive theme

### ISSUE THREAD

**Issue by net44** [yclas/yclas#2771]
It's 2018 and since few years RWD is a web standard, but yclas still has no basic simple default responsive theme ....

**Comment by neo22s** [comment]
Please this is not a suggestion forum, github is for developers. check our contribution guides. Thanks.

**Comment by net44** [comment]
Yes I know, but there is no suggestion forum, and contact to developers with small suggestions, bugs or ideas is not possible  :(  This script has a very big potential but without a community (where users can share ideas and help each other) it will not survive. Many users will choose another solution. 
And a basic responsive theme as standard it is a must in 2018.

**Comment by neo22s** [comment]
We have a contact form.

We have a responsive theme available withe the PRO license. Feel free to buy it and therefore contribute to the project ;)

We've been alive since 2008.... we can do things better for sure, but no resources, we had all of this you mention and only carried more work and less revenue. I need to feed my family.

regards
