### ISSUE TITLE
bug: image name too long

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3240]
2021-06-14 05:14:24 --- ERROR: Data too long for column 'file_name' at row 1 [ INSERT INTO `oc2_ad_images` (`id_ad`, `file_key`, `file_name`) VALUES ('915', 1, 'produtora-de-filmes-corporativos-para-empresas-de-energias-renovaveis-meio-ambiente-e-sustentabilidade-david-casan-studio-dead-pixel.1623658463_1.jpg') ]

**Comment by oliverds** [comment]
It seems we need to increase the `file_name` length to store timestamp and sequence.

**Comment by neo22s** [comment]
what if we better "cut" so it's sorter? we can cut always to 100 chars and keep the rest? wont be better that making it longer?

**Comment by oliverds** [comment]
But if we truncate the filename, then it won't be readable.

`produtora-de-filmes-corporativos-para-empresas-de-energias-renovaveis-meio-ambiente-e-sustentabilida` instead of `produtora-de-filmes-corporativos-para-empresas-de-energias-renovaveis-meio-ambiente-e-sustentabilidade-david-casan-studio-dead-pixel`

**Comment by neo22s** [comment]
ups ok! hehe then lets make it longer!

**Comment by neo22s** [comment]
We need this in yclas too

**Comment by oliverds** [comment]
Not really, ad_images table is an image management optimization only for yclas.com because of S3 storage. https://github.com/openclassifieds/yclas/issues/3170, https://github.com/openclassifieds/yclas/pull/3182
